language: ruby
sudo: false
cache: bundle
rvm:
  - 2.0
  - 2.2
  - 2.3
  - 2.4
  - 2.6
  - 2.7
deploy:
  provider: rubygems
  api_key:
    secure: VzCyoR6qhXLU5baJ+6QXqWozL3el4juGXXGmtzqmKHgrbTf5j+6R0VjzEjXu4AgTUcUnNSul1sumcyZ0WZySs63D9Tub1Lj2LHv2XlEdarurorObSzA8rKuZfxcjvfowsyzFz/HN+9fK6N36wcRJosyv9tQb8DLUw8EocnUOGcm+nsxY5Lk0WnY/XbWJoSuQyYwyUa7GEZyKZALO+jMq52kZf7XxaBXidk3zXPLKg1WBamVKuJa0t3/baLJBzw+gHoUcGrlOfz8e8ciH/7CVbyc9R2hfaQ2+uXECCYzy0U+Tii/iy7IuHeH1sNENkd7LXTU+znWl5kT6enlpCkfKlNznyvQrXSHNyOl3uT2B4ssD9nALeOtbQcl8+43oAiDaWYasxfqAZ5pSM/GCErHVFW/4fHqf4xmRyWCth1RLXS2JoqaH3O4WtpjGvaNYqlm0BYaOG9kXPiOALG0id7XyWbQSfub07IGMHFFQSF1548Gmly5CA6QdAlv5mxaVC82VBakTLDqZIQQxlU6XbfUzW0HGYoc109gy+3m2PIh/H6IP69ZOQOM1SrSLm0u+6mW3mr2xRZ+hJc1beZKftH3lZ7zFg0t/84lWAiUHc3zyO/IMJMPcqbsr5oLspaIjrmVwnVxHFNstHIKXuW7awD/3DkaQ1phsuTVgNA+4mFKuy54=
  gem: travis-release
  on:
    tags: true
    repo: tubbo/travis-release
addons:
  codeclimate:
    secure: odsbVeRQcdiRl978ZrMYGPweu3BPtfwuQ6TbnxmSgdv2uvq2gcUNu7aRNPXK1IUP5N7IIQgENLO8v5Rf0UHjYA+UcVdvrRh9Ph/Kx75RlR+blHNxqTVpdBjAW6VLfalPO+U4E3PPtpyrdi5kabngGdcjjDbyJmK5TYuvGisW91zPPfh3Ni3itYH4OsAll/bmd+OzMQ5eqVsLs6FawWFNJoMHl1jua+egx3IgZdRcPcy3PlRBArlSxwxAh6wtem/iRCNkowdZTr53HB6aDZQj/eHWzT25LyOhPK4RabK745AbK5F0VuplNURP5+9ykQ3GP5Wxj7euZtq742MtklhszWJHfBg3Ql7hYRlMO7uhs5ICtEHw0mEi5sc7Jb6EK435hPMZBEmgJ/eQuzrF3WjkE6Hyf3PRxCc85ypuxo4ZoY4phQ+s3GIm6+KpzrtcO5Tp3cAq/o9C5ObfbCJzaQGnhzW/c+7/eUdHxu7v1OlJXFkt3aAI2cbHG6xP091BzKQlk7noXR7TTfW2R3Hkut3mLi9WDRHf6ipIEv59rrTpmcff0Tvg7rZFi1p2ij1izKRUx7IJU+G0JTLj5Pg7Xin1p4xQF5E1KQCelNuR+7LH92pe8ry4HKPQESVArwdxYQVxHBGguAnWRPABWmd87/rf6co/3hS5Tqi+Fr4x9r/TWdc=
